//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTVRemoteControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartTVRemoteControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;root xmlns=&quot;urn:schemas-upnp-org:device-1-0&quot; xmlns:dlna=&quot;urn:schemas-dlna-org:device-1-0&quot; xmlns:sec=&quot;http://www.sec.co.kr/dlna&quot;&gt;
        ///&lt;specVersion&gt;
        ///&lt;major&gt;1&lt;/major&gt;
        ///&lt;minor&gt;0&lt;/minor&gt;
        ///&lt;/specVersion&gt;
        ///&lt;device&gt;
        ///&lt;dlna:X_DLNACAP/&gt;
        ///&lt;dlna:X_DLNADOC&gt;DMS-1.50&lt;/dlna:X_DLNADOC&gt;
        ///&lt;UDN&gt;&lt;/UDN&gt;
        ///&lt;dlna:X_DLNADOC&gt;M-DMS-1.50&lt;/dlna:X_DLNADOC&gt;
        ///&lt;friendlyName/&gt;
        ///&lt;deviceType&gt;urn:schemas-upnp-org:device:MediaServer:1&lt;/deviceType&gt;
        ///&lt;manufacturer&gt;SEC&lt;/manufacturer&gt;
        ///&lt;manufacturerURL&gt;http://www.samsung.com/se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SOAP-ENV:Envelope SOAP-ENV:encodingStyle=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;SOAP-ENV:Body&gt;
        ///    &lt;SOAP-ENV:Fault&gt;
        ///      &lt;faultcode&gt;500&lt;/faultcode&gt;
        ///      &lt;faultstring /&gt;
        ///      &lt;detail&gt;
        ///        &lt;UPnPError xmlns=&quot;urn:schemas-upnp-org:control-1-0&quot;&gt;
        ///          &lt;errorCode&gt;401&lt;/errorCode&gt;
        ///          &lt;errorDescription&gt;Invalid Action&lt;/errorDescription&gt;
        ///        &lt;/UPnPError&gt;
        ///      &lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Features xmlns=&quot;urn:schemas-upnp-org:av:avs&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;urn:schemas-upnp-org:av:avs http://www.upnp.org/schemas/av/avs.xsd&quot;&gt;
        ///  &lt;Feature name=&quot;samsung.com_BASICVIEW&quot; version=&quot;1&quot;&gt;
        ///    &lt;container id=&quot;I&quot; type=&quot;object.item.imageItem&quot;/&gt;
        ///    &lt;container id=&quot;A&quot; type=&quot;object.item.audioItem&quot;/&gt;
        ///    &lt;container id=&quot;V&quot; type=&quot;object.item.videoItem&quot;/&gt;
        ///  &lt;/Feature&gt;
        ///&lt;/Features&gt;.
        /// </summary>
        internal static string x_featurelist {
            get {
                return ResourceManager.GetString("x_featurelist", resourceCulture);
            }
        }
    }
}
